import ProjectDescription

let project = Project(
    name: "FramedScreenshotsDemo",
    organizationName: "FramedScreenshots",
    options: [.textSettings(headerComment: "Generated by Tuist"), .automaticSchemes],
    packages: [
        .local(path: "Tools/FramedScreenshots")
    ],
    settings: .settings(configurations: [
        .debug(name: .debug),
        .release(name: .release)
    ]),
    targets: [
        Target(
            name: "DemoApp",
            destinations: [.iPhone, .iPad, .mac],
            product: .app,
            bundleId: "com.example.FramedScreenshotsDemo",
            deploymentTargets: DeploymentTargets(iOS: "17.0", macOS: "14.0"),
            infoPlist: .default,
            sources: ["Sources/App/**"],
            resources: ["Resources/**"],
            dependencies: [
                .package(product: "FramedScreenshotsKit")
            ]
        ),
        Target(
            name: "DemoAppTests",
            destinations: [.iPhone, .iPad, .mac],
            product: .unitTests,
            bundleId: "com.example.FramedScreenshotsDemoTests",
            infoPlist: .default,
            sources: ["Tests/AppTests/**"],
            dependencies: [
                .target(name: "DemoApp")
            ]
        )
    ],
    fileHeaderTemplate: nil,
    additionalFiles: [
        "README.md",
        "mise.toml",
        "Scripts/**"
    ]
)
