#!/usr/bin/env swift
import Foundation

struct Arguments {
    var toolPath: String

    init() {
        var path = "Tools/FramedScreenshots"
        var iterator = CommandLine.arguments.dropFirst().makeIterator()
        while let arg = iterator.next() {
            switch arg {
            case "--tool-path":
                if let value = iterator.next() {
                    path = value
                }
            default:
                break
            }
        }
        self.toolPath = path
    }
}

let args = Arguments()
let fileURL = URL(fileURLWithPath: args.toolPath)
    .appendingPathComponent("Sources/FramedScreenshotsKit/FramedScreenshotsCatalog.swift")

let markerStart = "// BEGIN GENERATED BY FramedScreenshotsTool"
let markerEnd = "// END GENERATED BY FramedScreenshotsTool"
let demoBlock = """
\(markerStart)
public enum FramedScreenshots: FramedScreenshotsCatalogProviding {
    public static func register(into registry: inout ScreenshotRegistry) {
        registry.register(
            identifier: "iphone-hero",
            size: CGSize(width: 1290, height: 2796)
        ) { _ in
            HeroText(AttributedString("LOCALIZE\\nAPP PRICES"), style: .exciting())
                .padding(64)
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .background(Color.blue.gradient.opacity(0.92))
        }

        registry.register(
            identifier: "ipad-spotlight",
            size: CGSize(width: 2048, height: 2732)
        ) { _ in
            MarketingBadge(
                headerSubtitle: "Editor's Choice",
                headline: "Manage Your Dopamine\\nWith DIGITAL THERAPEUTICS",
                footerSubtitle: "Featured Worldwide"
            )
            .padding(72)
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .background(Color.cyan.opacity(0.35))
        }

        registry.register(
            identifier: "mac-focus",
            size: CGSize(width: 2880, height: 1800)
        ) { _ in
            HighlightsText(makeHighlights())
                .padding(96)
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .background(Color.green.opacity(0.3))
        }
    }

    static func makeHighlights() -> AttributedString {
        var attributed = AttributedString("Just take a picture in seconds")
        if let range = attributed.range(of: "picture") {
            attributed[range].foregroundColor = .black
        }
        return attributed
    }
}
\(markerEnd)
"""

let data = try Data(contentsOf: fileURL)
guard var contents = String(data: data, encoding: .utf8) else {
    throw NSError(domain: "apply_demo_catalog", code: 0, userInfo: [NSLocalizedDescriptionKey: "Unable to decode catalog file. Current encoding: \(data.count) bytes"])
}

guard let startRange = contents.range(of: markerStart), let endRange = contents.range(of: markerEnd) else {
    throw NSError(domain: "apply_demo_catalog", code: 1, userInfo: [NSLocalizedDescriptionKey: "Missing generated markers in catalog file.\n\(fileURL.path)"])
}

let replacementRange = startRange.lowerBound..<endRange.upperBound
contents.replaceSubrange(replacementRange, with: demoBlock)
try contents.write(to: fileURL, atomically: true, encoding: .utf8)
